DB:DatabaseApp

Insert USER_MENU_RECORD(USER_ID,MENU_ID,RECORD_TIME,USER_IP,REF_URL,BROWSER,VERSION,PLATFORM,AGENT)
VALUES(*USER_ID*,*MENU_ID*,*RECORD_TIME*,*USER_IP*,*REF_URL*,*BROWSER*,*VERSION*,*PLATFORM*,*AGENT*)